#!/bin/bash
# CANDIDATE recipe extracted from the BLFS 13.1-systemd book.
# source : book/blfs-13.1/gnome/gsettings-desktop-schemas.html
# title  : gsettings-desktop-schemas-50.1
# The driver supplies unpack/cd/cleanup. Commands below are in-package only.
set -e

# --- block 0 --------------------------------------------------
#   ctx: p-schemas/50/gsettings-desktop-schemas-50.1.tar.xz Download MD5 sum:
#   ctx: b3851a1d2dd684f7ea1a1d032e2a7dfb Download size: 876 KB Estimated disk space required: 17
#   ctx: MB Estimated build time: less than 0.1 SBU GSettings Desktop Schemas Dependencies
#   ctx: Required GLib-2.88.3 (with GObject Introspection) Installation of GSettings Desktop
#   ctx: Schemas Install GSettings Desktop Schemas by running the following commands:
sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in &&

mkdir build &&
cd    build &&

meson setup --prefix=/usr --buildtype=release .. &&
ninja

# --- block 1 --------------------------------------------------
#   ctx: This package does not come with a test suite. Now, as the root user:
ninja install

# --- block 2 --------------------------------------------------
#   ctx: Note If you installed the package to your system using a “DESTDIR” method,
#   ctx: /usr/share/glib-2.0/schemas/gschemas.compiled was not updated/created. Create (or
#   ctx: update) the file using the following command as the root user:
#   REVIEWED [drop]: DESTDIR-only caveat; this project installs directly, so the compiled schema cache is already correctly generated by ninja install.
# glib-compile-schemas /usr/share/glib-2.0/schemas

