#!/bin/bash
# HAND-AUTHORED recipe -- no BLFS book page for sshpass (BLFS 13.0-systemd carries no
# sshpass page; grepped the whole book tree, zero hits).
# source: sourceforge.net/projects/sshpass, release 1.10 -- the project's own canonical
# distribution point and the newest release published there (the file listing runs
# 0.01 ... 1.09, 1.10; nothing newer exists). Upstream is a SourceForge project with no
# GitHub releases and no signed tarballs.
#
# provenance: sha256 of the downloaded tarball is
# ad1106c203cbb56185ca3bad8c6ccafca3b4064696194da879f81c8d7bdfeeda. Upstream publishes
# no sha256 and no signature, so the independent check here is SourceForge's own file
# API, whose sha1 40d6f209340c06a6abc9515ddf1000f967bea58e and md5
# e435c55deb6e2e410508ecc5da3066f8 both match what was downloaded. That is weaker than
# the OpenPGP record blfs-tor.sh carries; recorded as what it is rather than dressed up.
#
# rationale: operator-requested (2026-09-08). Feeds a password to ssh's own interactive
# prompt from a non-tty, for the case where key-based authentication is not available on
# the far end. Nothing in this build provided it.
#
# Security note, from sshpass's own man page rather than added here: `-p` puts the
# password in the process command line, where any local user can read it, and is the
# least safe of the three ways in. `-f <file>` (a mode-600 file) and `-e`
# ($SSHPASS in the environment) are the ones worth using. sshpass also disables ssh's
# host-key verification prompt handling in the sense that an unknown host key makes it
# exit non-zero (return code 6) rather than silently accepting -- it does not weaken
# StrictHostKeyChecking on its own.
#
# Portable: nothing here names this host's hardware, disks or display. Shared recipe per
# CLAUDE.md's shared/host test.
#
# Build notes, each checked against this tarball:
#
#   plain autotools, one translation unit (main.c) and no libraries at all --
#   configure.ac's "Checks for libraries" section is empty, so the only dependency is
#   glibc. Nothing had to be built ahead of this step.
#
#   the shipped configure (generated by autoconf 2.71) is used as-is. Verified that
#   make does not try to regenerate it: configure.ac, aclocal.m4, config.h.in and
#   configure all carry the same mtime in the tarball, and Makefile.in is newer than
#   Makefile.am, so automake's rebuild rules never fire. `autoreconf -fi` under this
#   host's autoconf 2.72 / automake 1.18.1 does succeed (four obsolete-macro warnings:
#   AC_HEADER_STDC, AC_PROG_GCC_TRADITIONAL, AC_TYPE_SIGNAL, AM_CONFIG_HEADER), so
#   regenerating is possible -- it is simply unnecessary, and using the tarball's own
#   configure keeps the build reproducible against the release.
#
#   --enable-password-prompt is deliberately not passed. It replaces the substring
#   sshpass watches the pty for, default "assword", which matches this system's own
#   openssh-10.5p1 prompt ("%s@%s's password: ", confirmed in /usr/bin/ssh) as well as
#   the sudo/su prompts. An override here would only be needed for a non-English or
#   patched ssh.
#
#   installs exactly two files, /usr/bin/sshpass and /usr/share/man/man1/sshpass.1
#   (bin_PROGRAMS + man_MANS, confirmed with a DESTDIR install). No config, no unit, no
#   account.
set -e

./configure --prefix=/usr &&
make

make install

echo "### version"
/usr/bin/sshpass -V
