#!/bin/bash
# HAND-AUTHORED recipe -- no BLFS book page covers this step.
# rationale: Operator-requested (2026-09-04). Wayland-native image viewer (MIT). All of
# imv's required deps (pangocairo, gl, xkbcommon, icu-io, wayland-client/-egl, egl) and
# its enabled image backends (libtiff, libpng, libjpeg-turbo, librsvg -- all "feature:
# auto" in meson_options.txt) are already built; freeimage/libnsgif/libheif are not
# present and stay disabled rather than pulling in three more packages for backends
# nothing needs (png/jpg/tiff/svg/gif already covered). meson.build's inih dependency
# is pulled from its own subprojects/inih.wrap (github.com/benhoyt/inih + a WrapDB
# patch) -- needs network at configure time, confirmed present.
# `-Dwindows=wayland` (not the 'all' default): this host has no libGLU (`glu.pc`
# missing), which the x11 backend requires unconditionally -- and there is no X11
# session to view images in anyway, only XWayland-under-Hyprland. Building the x11
# backend just to leave it unused was the wrong trade against pulling in GLU for
# nothing (that's a real BLFS/x7lib-adjacent chain, not a one-line dependency).
# `-Dc_link_args=-licuuc`: real link failure, not a guess -- console.c calls ICU's
# ubrk_* (break iterator) API, which lives in libicuuc, but imv's meson.build only
# declares `dependency('icu-io')`. This host's icu-io.pc lists icu-i18n under
# Requires.private (not Requires), which pkg-config correctly omits from a plain
# `--libs` (that field is for --static consumers) -- so nothing on the link line ever
# pulls libicuuc.so in, and `ld -no-undefined` (meson's own default) refused to link
# with `ubrk_close_78` unresolved. Fixed at the link-args level rather than patching
# imv's meson.build, since the real defect is this host's icu-io.pc shape, not imv.
#
# Real, second failure -- found only by actually opening an image, not just checking
# `imv -v` (which never touches the Wayland path at all): `interface 'xdg_toplevel'
# has no event 3`, imv hangs, nothing renders. Root cause confirmed by reading imv's
# own source: `src/xdg-shell-protocol.c` and `src/xdg-shell-client-protocol.h` are
# checked into imv's release tarball as pre-generated files ("Generated by
# wayland-scanner 1.17.0" in the file header) rather than produced from the build
# host's own wayland-protocols at build time -- meson.build compiles them directly,
# no custom_target/wayland-scanner step exists at all. That 1.17.0-era xdg_toplevel
# table has exactly 2 events (configure, close); event 3 (configure_bounds, added in
# xdg-shell v4) and event 4 (wm_capabilities, added v5) don't exist in it.
# `wl_window.c` binds `xdg_wm_base` at whatever version the compositor advertises,
# uncapped to what the bundled table actually supports -- Hyprland (built against a
# current, version-7 xdg-shell) duly advertises up through wm_capabilities, sends it,
# and imv's ancient generated code has no slot for it. Fixed by regenerating both
# files from this host's real, already-installed wayland-protocols (version 7,
# confirmed against /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml) with
# the system's own wayland-scanner before the build, overwriting imv's stale copies
# in place -- not a patch to imv's C code, and not something the project's book/hand
# split has a better home for (this isn't book-derived content, and hand() is exactly
# "the recipe does something a book-plus-decision can't express"). No upstream fix
# exists (checked eXeC64/imv issues for xdg_toplevel/xdg-shell/wayland-scanner/
# hyprland before writing this).
#
# Same root cause, second casualty: once the regenerated table let xdg_toplevel
# receive wm_capabilities, `imv` crashed again, this time `listener function for
# opcode 4 of wl_output is NULL` (SIGABRT). `wl_window.c`'s `on_global()` binds
# every interface at the compositor's raw advertised version, uncapped, for every
# global -- not just xdg_wm_base. `output_listener` only implements wl_output's v1-3
# events (geometry/mode/done/scale); `name`/`description` (v4+) are unset. Hyprland
# advertises wl_output v4, so it sends `name`, and imv's own dispatcher aborts on the
# NULL slot. Checked every other listener in the same file before deciding this was
# the last one: `xdg_toplevel_listener` covers only configure/close (v1) -- also
# short of configure_bounds (v4)/wm_capabilities (v5), which is exactly what
# capping xdg_wm_base's *bind* version below actually prevents from ever being
# offered (xdg_toplevel/xdg_surface inherit their parent xdg_wm_base's bound
# version); `wl_seat_listener` covers both real wl_seat events (v1 capabilities, v2
# name) in full, but wl_seat's bind version is also what `wl_pointer`/`wl_keyboard`
# sub-objects inherit, and `pointer_listener` stops at axis_discrete (v5) -- short of
# axis_value120 (v8) and axis_relative_direction (v9); `keyboard_listener` and
# `xdg_surface_listener` are complete at every version that exists.
#
# Third casualty after fixing that: `listener function for opcode 2 of wl_surface is
# NULL`. Same mechanism again -- `wl_compositor` has zero events of its own (pure
# factory interface, so its own bind version looked harmless) but the `wl_surface`
# it creates via `wl_compositor_create_surface` inherits *its* bound version, and
# `surface_listener` implements only enter/leave (v1) -- short of
# preferred_buffer_scale/preferred_buffer_transform (both added v6). That is every
# global `on_global` binds (compositor, xdg_wm_base, seat, output) -- all four
# needed the same cap, not three.
#
# Four `sed`-applied caps below, each capped to the highest version its own listener
# struct (or, for compositor/xdg_wm_base/seat, the child object it creates)
# implements (verified by reading every listener in this file, not guessed):
# `wl_compositor` at 4 (blocks v6's two new surface events), `xdg_wm_base` at 3 (so
# its xdg_toplevel/xdg_surface children never see v4+), `wl_seat` at 5 (keeps v2's
# `name` and v4's `repeat_info`, blocks v8/v9's pointer axis events), `wl_output` at
# 3 (blocks v4's `name`/`description`). Same fix category as the protocol
# regeneration above -- a real client-side Wayland version-negotiation bug, not
# something specific to this host beyond having a compositor modern enough to
# expose it.
set -e

sed -i \
    -e 's/\&wl_compositor_interface, version)/\&wl_compositor_interface, version < 4 ? version : 4)/' \
    -e 's/\&xdg_wm_base_interface, version)/\&xdg_wm_base_interface, version < 3 ? version : 3)/' \
    -e 's/\&wl_seat_interface, version)/\&wl_seat_interface, version < 5 ? version : 5)/' \
    -e 's/\&wl_output_interface, version)/\&wl_output_interface, version < 3 ? version : 3)/' \
    src/wl_window.c

wayland-scanner private-code \
    /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
    src/xdg-shell-protocol.c
wayland-scanner client-header \
    /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
    src/xdg-shell-client-protocol.h

meson setup -Dwindows=wayland -Dc_link_args=-licuuc --prefix=/usr --buildtype=release . build
ninja -C build
ninja -C build install
install -Dm644 LICENSE /usr/share/licenses/imv/LICENSE

echo "### version"
imv --version 2>&1 || true
