#!/bin/bash
# CANDIDATE recipe extracted from the BLFS 13.0-systemd book.
# source : book/blfs-13.0/x/gdk-pixbuf.html
# title  : gdk-pixbuf-2.44.5
# The driver supplies unpack/cd/cleanup. Commands below are in-package only.
#
# Rebuilt 2026-08-26: the book's own recipe disables every built-in loader
# (png/gif/jpeg/tiff) on the assumption glycin (a newer external loader
# service) replaces them -- but this project deliberately skipped glycin
# back in tier 6 (circular Rust rebuild, out of scope), leaving BOTH paths
# disabled. Net effect: gdk-pixbuf could load precisely nothing --
# /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache existed but listed zero
# loaders, confirmed directly, and even GTK's own bundled PNG icons failed
# to load with "Unrecognized image file format" -- the real bug behind
# wofi's crash (Gtk:ERROR ensure_surface_for_gicon, SIGABRT). Not a wofi
# bug at all; anything using icons anywhere in this desktop stack was
# equally broken, just hadn't hit a hard crash yet. Re-enabled png/gif/
# jpeg (libpng, giflib, libjpeg-turbo all already built) -- tiff left
# disabled, libtiff was never built and isn't otherwise needed.
set -e

# --- block 0 --------------------------------------------------
#   ctx: its recommended dependencies, and rebuild gdk-pixbuf again) Optional Gi-DocGen-2026.1
#   ctx: (to generate documentation), libavif-1.3.0 (runtime, deprecated), libjpeg-turbo-3.1.3
#   ctx: (deprecated), libjxl-0.11.2 (runtime, deprecated), libpng-1.6.55 (deprecated),
#   ctx: librsvg-2.61.4 (runtime, deprecated), and libtiff-4.7.1 (deprecated) Installation of Gdk
#   ctx: Pixbuf Install Gdk Pixbuf by running the following commands:
mkdir build &&
cd    build &&

meson setup ..                \
      --prefix=/usr           \
      --buildtype=release     \
      -D man=false            \
      -D png=enabled          \
      -D gif=enabled          \
      -D jpeg=enabled         \
      -D tiff=disabled        \
      -D thumbnailer=disabled \
      --wrap-mode=nofallback  \
      -D glycin=disabled &&
ninja

# --- block 1 --------------------------------------------------
#   ctx: If you have Gi-DocGen-2026.1 installed and wish to build the API documentation for this
#   ctx: package, issue:
#   REVIEWED [drop]: gtk_doc=true needs Gi-DocGen, not installed.
# sed "/docs_dir =/s@\$@ / 'gdk-pixbuf-2.44.5'@" -i ../docs/meson.build &&
# meson configure -D gtk_doc=true                                        &&
# ninja

# --- block 2 --------------------------------------------------
#   ctx: To test the results, issue: ninja test Now, as the root user:
ninja install

# --- block 3 --------------------------------------------------
#   ctx: Note If you installed the package on to your system using a “DESTDIR” method, an
#   ctx: important file was not installed and should be copied and/or generated. Generate it
#   ctx: using the following command as the root user:
#   REVIEWED [drop]: DESTDIR-only caveat; this project installs directly (no DESTDIR), so the cache is already correctly generated by ninja install.
# gdk-pixbuf-query-loaders --update-cache

